name: pull request approve and merge test

on:
  workflow_dispatch:

jobs:
  pull-request-approve-merge-test:
    runs-on: ubuntu-latest
    steps:
    - name: Get timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +'%Y-%m-%dT%H-%M-%S')"
    - name: Create branch
      uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'test-branch-${{ steps.timestamp.outputs.timestamp }}'
    - name: Approve PR
      run: gh pr review 'test-branch-${{ steps.timestamp.outputs.timestamp }}' --approve
