name: ref sha test


on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sha-ref-test:
    runs-on: ubuntu-latest
    steps:
      - name: check sha and ref
        run: |
          echo '1' $GITHUB_REF
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.ref_name }}
          echo '4' ${{ github.head_ref }}
          echo '5' ${{ github.base_ref }}
          echo '6' ${{ github.sha }}
