name: ref sha test

on:
  push:
    branches:
      - main

jobs:
  sha-ref-test:
    runs-on: ubuntu-latest
    steps:
      - name: check sha and ref
        run: |
          echo "${GITHUB_REF#refs/heads/}-$(git rev-parse --short '$GITHUB_SHA')"
