name: Ruff Check
on:
  push:
    branches:
      - main

jobs:
  ruff-check:
    name: Ruff Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: "./src"
          version: 0.2.2
          args: --select B
